### PR TITLE
Feature y

### PR DESCRIPTION
**Pull request by theBeatle**
please add my super puper code

### CODE REVIEW

**Review by oshafranskyi — COMMENTED** [review]
Ok

**Review by K0rik — COMMENTED** [review]
Narmalno

**Comment by FailyFox** [comment]
Everything is cool

**Comment by Illyha** [comment]
BLABLABLA!!!!ALAH AKBAR!!

**Comment by FailyFox** [comment]
🤦

**Review by APU777 — COMMENTED** [review]
The best code curriculum that I've ever had.

**Comment by Illyha** [comment]
artworks-000322933404-2qsvhm-t500x500

**Pull request merged**
